title: Alpha Omega Epsilon at Lehigh University
description: > # this means to ignore newlines until "baseurl:"
  Beta Lambda Chapter of Alpha Omega Epsilon at Lehigh University
baseurl: "" # the subpath of your site, e.g. /blog
url: "aoebetalambda.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/icon.png"

social: 
  name: Your Facebook Page
  link: "https://www.facebook.com/a.o.e.lehigh/"

google_site_verification: google8c4e1fe8be15c191.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/a.o.e.lehigh/
  - title: instagram
    url: https://www.instagram.com/aoe_lehighu

# Build settings
markdown: kramdown
permalink: pretty
