title: Epic-Tesseract
description: > # this means to ignore newlines until "baseurl:"
  MedHacks project
baseurl: "" # the subpath of your site, e.g. /blog
url: "bzc220.github.io/epic-tesseract" # the base hostname & protocol for your site

facebook:
  app_id: 

# logo: "../css/2016_style/img/icon.png"

google-site-verification: K4Suf_5mSklj0wEivB_fPbdqitjluybzL-zMWIq92s0

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag


# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-hacker
